### ISSUE TITLE
latest cyroaring version faster?

### ISSUE THREAD

**Issue by andreasvc** [Ezibenroc/roaring_analysis#2]
These benchmarks are very interesting, thanks for making them! I ran them on my machine with the latest CyRoaring version, and it seems that it's now as fast as PyRoaring in each benchmark. However, this is on a Sandy Bridge CPU, and it does not have AVX2, so it could also be that PyRoaring is performing worse. I'm curious about the results when you re-run the benchmarks on your systems.

![sb](https://cloud.githubusercontent.com/assets/261460/23275445/dd70b220-fa06-11e6-95ef-aedf57457401.png)

**Comment by Ezibenroc** [comment]
Thank you for running the benchmarks! These results are here to be reproduced and discussed.

According to the [CRoaring preliminary analysis](https://github.com/Ezibenroc/roaring_analysis/blob/e3df09637347d4eb9f26849a7e7bb2e619f5ca79/preliminary_analysis.ipynb), AVX is the factor that has the highest impact on performances for sparse datasets, but has no impact (or even negative impact) for dense datasets.
So this could explain why PyRoaring performed better with sparse datasets on Skylake and Broadwell but not on Sandy Bridge.

I will update the libraries and re-run the benchmarks, to see if this difference comes from the CPU or the library version.

**Comment by andreasvc** [comment]
Hm that's odd, because when I look at CRoaring's code for array unions, I only see an SSE optimized version, not code using AVX2. I experimented with incorporating that SSE version, but it gives a slowdown in my admittedly too small benchmark with bitmaps of 200 elements.

Other possible explanations are the run-encoded blocks of CRoaring, or other CPU differences like size of cache etc.

**Comment by Ezibenroc** [comment]
I did some experiments.

On a Raspberry Pi (ARM processor, so no AVX), with the versions of CRoaring, PyRoaring and CyRoaring from this repository, I get the following plot. The datasets have a size sampled in [1, 10^6] (i.e. the maximal size is 10 times smaller than before) because of the low amount of memory available.
![raspberry](https://cloud.githubusercontent.com/assets/8900834/23396950/7b20a434-fd96-11e6-8a8a-948e67696c39.png)

On the Skylake machine, with the versions of CRoaring and PyRoaring from this repository, the latest version of CyRoaring ([`d37cf1b78422c1124a279548bb3f41591d516526`](https://github.com/andreasvc/roaringbitmap/commit/d37cf1b78422c1124a279548bb3f41591d516526)), I get this plot:
![skylake](https://cloud.githubusercontent.com/assets/8900834/23396951/7b211e50-fd96-11e6-83ce-7bf50786ca32.png)

Thus, I think this difference between CyRoaring and PyRoaring comes from AVX and not the latest version of CyRoaring.

------

In the version of CRoaring currently used, there are two possible functions to compute the union between two array containers: `union_vector16` and `union_uint16`. The former uses SSE instructions. Choice between the two is made with `#ifdef ROARING_VECTOR_UNION_ENABLED`.

This macro is defined in file `include/roaring/portability.h`:

```c
#ifdef USEAVX
#define USE_BMI  // we assume that AVX2 and BMI go hand and hand
#define USEAVX2FORDECODING            // optimization
#define ROARING_VECTOR_UNION_ENABLED  // vector unions (optimization)
#endif

#endif // DISABLE_X64
```

So the SSE version will be used only if AVX is supported.

In the current version of CRoaring, the macro has been renamed to `ROARING_VECTOR_OPERATIONS_ENABLED`, but we have the [same piece of code](https://github.com/RoaringBitmap/CRoaring/blob/master/include/roaring/portability.h#L71-L77).

I am not very familiar with these technologies, but SSE is about 10 years older than AVX, so maybe it would be nice to have a finner grain of choice: allowing to use SSE instructions if they are available but AVX is not?

**Comment by andreasvc** [comment]
Thanks, this solves the original issue, which was to see the plots with the latest CyRoaring version.

Am I correct in assuming that with density 0.01, only sparse arrays are used, no run-length encoding or bitmaps?

Then it indeed seems most likely that the difference is because of the SSE array union code in CRoaring. I'll consider adding it to CyRoaring; or wait for a sufficiently smart compiler to do the optimization...

**Comment by Ezibenroc** [comment]
> Am I correct in assuming that with density 0.01, only sparse arrays or used, no run-length encoding or bitmaps?

It is not impossible to have bitmaps or run-length encoding with this density, but very unlikely.

To be a bitmap, the container need to have a density above 2^12 / 2^16 = 0.0625. This could happen if the data is not well spread (e.g. one container with much more elements than the others), but it is unlikely here since the elements are sampled uniformly.

Similarly, a container could be a run container if a lot of its elements were contiguous. For the same reason it is unprobable.
